export declare const WellKnownTags: {
    readonly Public: "Public";
    readonly Protected: "Protected";
    readonly Private: "Private";
    readonly Internal: "Internal";
    readonly File: "File";
    readonly Project: "Project";
    readonly Folder: "Folder";
    readonly Assembly: "Assembly";
    readonly Class: "Class";
    readonly Constant: "Constant";
    readonly Delegate: "Delegate";
    readonly Enum: "Enum";
    readonly EnumMember: "EnumMember";
    readonly Event: "Event";
    readonly ExtensionMethod: "ExtensionMethod";
    readonly Field: "Field";
    readonly Interface: "Interface";
    readonly Intrinsic: "Intrinsic";
    readonly Keyword: "Keyword";
    readonly Label: "Label";
    readonly Local: "Local";
    readonly Namespace: "Namespace";
    readonly Method: "Method";
    readonly Module: "Module";
    readonly Operator: "Operator";
    readonly Parameter: "Parameter";
    readonly Property: "Property";
    readonly RangeVariable: "RangeVariable";
    readonly Reference: "Reference";
    readonly Structure: "Structure";
    readonly TypeParameter: "TypeParameter";
    readonly Snippet: "Snippet";
    readonly Error: "Error";
    readonly Warning: "Warning";
};
type ToUnion<T> = T[keyof T];
export type WellKnownTag = ToUnion<typeof WellKnownTags>;
export declare const WellKnownTagArrays: {
    readonly Assembly: readonly ["Assembly"];
    readonly ClassPublic: readonly ["Class", "Public"];
    readonly ClassProtected: readonly ["Class", "Protected"];
    readonly ClassPrivate: readonly ["Class", "Private"];
    readonly ClassInternal: readonly ["Class", "Internal"];
    readonly ConstantPublic: readonly ["Constant", "Public"];
    readonly ConstantProtected: readonly ["Constant", "Protected"];
    readonly ConstantPrivate: readonly ["Constant", "Private"];
    readonly ConstantInternal: readonly ["Constant", "Internal"];
    readonly DelegatePublic: readonly ["Delegate", "Public"];
    readonly DelegateProtected: readonly ["Delegate", "Protected"];
    readonly DelegatePrivate: readonly ["Delegate", "Private"];
    readonly DelegateInternal: readonly ["Delegate", "Internal"];
    readonly EnumPublic: readonly ["Enum", "Public"];
    readonly EnumProtected: readonly ["Enum", "Protected"];
    readonly EnumPrivate: readonly ["Enum", "Private"];
    readonly EnumInternal: readonly ["Enum", "Internal"];
    readonly EnumMemberPublic: readonly ["EnumMember", "Public"];
    readonly EnumMemberProtected: readonly ["EnumMember", "Protected"];
    readonly EnumMemberPrivate: readonly ["EnumMember", "Private"];
    readonly EnumMemberInternal: readonly ["EnumMember", "Internal"];
    readonly EventPublic: readonly ["Event", "Public"];
    readonly EventProtected: readonly ["Event", "Protected"];
    readonly EventPrivate: readonly ["Event", "Private"];
    readonly EventInternal: readonly ["Event", "Internal"];
    readonly ExtensionMethodPublic: readonly ["ExtensionMethod", "Public"];
    readonly ExtensionMethodProtected: readonly ["ExtensionMethod", "Protected"];
    readonly ExtensionMethodPrivate: readonly ["ExtensionMethod", "Private"];
    readonly ExtensionMethodInternal: readonly ["ExtensionMethod", "Internal"];
    readonly FieldPublic: readonly ["Field", "Public"];
    readonly FieldProtected: readonly ["Field", "Protected"];
    readonly FieldPrivate: readonly ["Field", "Private"];
    readonly FieldInternal: readonly ["Field", "Internal"];
    readonly InterfacePublic: readonly ["Interface", "Public"];
    readonly InterfaceProtected: readonly ["Interface", "Protected"];
    readonly InterfacePrivate: readonly ["Interface", "Private"];
    readonly InterfaceInternal: readonly ["Interface", "Internal"];
    readonly Intrinsic: readonly ["Intrinsic"];
    readonly Keyword: readonly ["Keyword"];
    readonly Label: readonly ["Label"];
    readonly Local: readonly ["Local"];
    readonly Namespace: readonly ["Namespace"];
    readonly MethodPublic: readonly ["Method", "Public"];
    readonly MethodProtected: readonly ["Method", "Protected"];
    readonly MethodPrivate: readonly ["Method", "Private"];
    readonly MethodInternal: readonly ["Method", "Internal"];
    readonly ModulePublic: readonly ["Module", "Public"];
    readonly ModuleProtected: readonly ["Module", "Protected"];
    readonly ModulePrivate: readonly ["Module", "Private"];
    readonly ModuleInternal: readonly ["Module", "Internal"];
    readonly Folder: readonly ["Folder"];
    readonly Operator: readonly ["Operator"];
    readonly Parameter: readonly ["Parameter"];
    readonly PropertyPublic: readonly ["Property", "Public"];
    readonly PropertyProtected: readonly ["Property", "Protected"];
    readonly PropertyPrivate: readonly ["Property", "Private"];
    readonly PropertyInternal: readonly ["Property", "Internal"];
    readonly RangeVariable: readonly ["RangeVariable"];
    readonly Reference: readonly ["Reference"];
    readonly StructurePublic: readonly ["Structure", "Public"];
    readonly StructureProtected: readonly ["Structure", "Protected"];
    readonly StructurePrivate: readonly ["Structure", "Private"];
    readonly StructureInternal: readonly ["Structure", "Internal"];
    readonly TypeParameter: readonly ["TypeParameter"];
    readonly Snippet: readonly ["Snippet"];
    readonly Error: readonly ["Error"];
    readonly Warning: readonly ["Warning"];
};
export type WellKnownTagArray = ToUnion<typeof WellKnownTagArrays>;
export {};
